android.nonTransitiveRClass=true
android.uniquePackageNames=true
android.useAndroidX=true
org.gradle.caching=true
org.gradle.parallel=true
org.gradle.configuration-cache=false
kotlin.daemon.useFallbackStrategy=false
org.gradle.kotlin.dsl.allWarningsAsErrors=true
org.gradle.jvmargs=-Xmx8192M -Dkotlin.daemon.jvm.options\="-Xmx2048M"

# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

android.newDsl=false
android.builtInKotlin=false
android.disallowKotlinSourceSets=false
android.sync.suppressAgpWarnings=UNSUPPORTED_PROJECT_OPTION_USE,DEPRECATED_DSL

# 16kb page size support
# Note: android.bundle.enableUncompressedNativeLibs is removed in 8.1+
# and enabled by default for extractNativeLibs=false
android.extractNativeLibs=false
